# Copies the sliced BirdNET model into the iOS bundle and writes the species
# table the Audio ID screen reads. Run from this directory:
#   python3 export_birdnet.py <repo root>
import json, shutil, sys
repo=sys.argv[1]; keep=json.load(open("keep_species.json")); TH=0.5
shutil.copy("audio_birds.onnx",f"{repo}/ios/iNaturalistReactNative/audio_birds.onnx")
esc=lambda x: (x or "").replace('"','\\"')
rows="\n".join(f'  ["{s["name"]}", "{esc(s["common"] or s["name"])}", {s["id"]}],' for s in keep)
open(f"{repo}/src/components/AudioId/audioIdSpecies.ts","w").write(f"""// Generated by scripts/bird_audio/birdnet/export_birdnet.py — order matches the outputs
// of ios/iNaturalistReactNative/audio_birds.onnx: every bird species with 10+
// research-grade iNaturalist observations within 40 km of Seattle that BirdNET
// v3.0 knows. [scientific name, common name, iNaturalist taxon ID]
const ROWS: [string, string, number][] = [
{rows}
];

// BirdNET score a species needs to count as heard.
const THRESHOLD = {TH};

const AUDIO_ID_SPECIES = ROWS.map( ( [name, commonName, taxonId] ) => ( {{
  name, commonName, taxonId, threshold: THRESHOLD,
}} ) );

export default AUDIO_ID_SPECIES;
""")
