# Copies the trained model into the iOS bundle and writes the species table the
# Audio ID screen reads. Run from this directory: python3 export_app.py <repo root>
import json, shutil, sys
repo=sys.argv[1]; rep=json.load(open("report20.json")); top=json.load(open("counts.json"))[:20]
assert [t[3] for t in top]==rep["species"]
shutil.copy("audio_birds.onnx",f"{repo}/ios/iNaturalistReactNative/audio_birds.onnx")
rows="\n".join(f'  ["{n}", "{c}", {i}, {th}],'
               for (_,n,i,c),th in zip(top,rep["thresholds"]))
open(f"{repo}/src/components/AudioId/audioIdSpecies.ts","w").write(f"""// Generated by scripts/bird_audio/export_app.py — order matches the outputs of
// ios/iNaturalistReactNative/audio_birds.onnx. Thresholds are per-species score
// cutoffs tuned for F1 on held-out validation soundscapes.
// [scientific name, common name, taxon ID, threshold]
const ROWS: [string, string, number, number][] = [
{rows}
];

const AUDIO_ID_SPECIES = ROWS.map( ( [name, commonName, taxonId, threshold] ) => ( {{
  name, commonName, taxonId, threshold,
}} ) );

export default AUDIO_ID_SPECIES;
""")
