#!/usr/bin/env node
// Stamps the git commit the app is built from into a source module that gets
// bundled and attached to every remote log entry, so a log line can be traced
// back to the exact code that produced it. The generated file is gitignored.
//
// This runs from metro.config.js, which no bundle can avoid loading — a stamp
// that only ran on `npm install` sat 34 commits stale across a redeploy that
// demonstrably changed behavior, so the logs named code that was not running.
// A wrong stamp is worse than no stamp, since it is believed.
const { execSync } = require( "child_process" );
const fs = require( "fs" );
const path = require( "path" );

const git = command => execSync( command, {
  encoding: "utf8",
  cwd: path.join( __dirname, ".." ),
  stdio: ["ignore", "pipe", "ignore"],
} ).trim( );

const outPath = path.join( __dirname, "..", "src", "sharedHelpers", "appCommit.ts" );

function writeAppCommit( ) {
  let commit = "unknown";
  try {
    commit = git( "git rev-parse --short HEAD" ) || "unknown";
    // Uncommitted work means the bundle is not the commit. Say so rather than
    // pointing a later reader at a diff that never ran.
    if ( git( "git status --porcelain" ) ) {
      commit += "-dirty";
    }
  } catch {
    // No git (e.g. a source tarball build) — leave the fallback in place.
  }

  const contents = `// AUTO-GENERATED by scripts/writeAppCommit.js at bundle time. Do not
// edit or commit. The short git commit the bundle was built from.
const APP_COMMIT = ${JSON.stringify( commit )};

export default APP_COMMIT;
`;

  // Only write on a real change: Metro watches this file, and rewriting it
  // with identical contents on every bundle would invalidate the module and
  // churn rebuilds for nothing.
  if ( !fs.existsSync( outPath ) || fs.readFileSync( outPath, "utf8" ) !== contents ) {
    fs.writeFileSync( outPath, contents );
  }
  return commit;
}

if ( require.main === module ) {
  writeAppCommit( );
}

module.exports = writeAppCommit;
