#!/usr/bin/env node
// Stamps the git commit the app is built from into a source module that gets
// bundled and attached to every remote log entry, so a log line can be traced
// back to the exact code that produced it. Run at install/build time (see the
// postinstall script); the generated file is gitignored.
const { execSync } = require( "child_process" );
const fs = require( "fs" );
const path = require( "path" );

let commit = "unknown";
try {
  commit = execSync( "git rev-parse --short HEAD", { encoding: "utf8" } ).trim( ) || "unknown";
} catch {
  // No git (e.g. a source tarball build) — leave the fallback in place.
}

const outPath = path.join( __dirname, "..", "src", "sharedHelpers", "appCommit.ts" );
const contents = `// AUTO-GENERATED by scripts/writeAppCommit.js at install/build time. Do not
// edit or commit. The short git commit the bundle was built from.
const APP_COMMIT = ${JSON.stringify( commit )};

export default APP_COMMIT;
`;

fs.writeFileSync( outPath, contents );
