// Generated by scripts/bird_audio/export_app.py — order matches the outputs of
// ios/iNaturalistReactNative/audio_birds.onnx. Thresholds are per-species score
// cutoffs tuned for F1 on held-out validation soundscapes.
// [scientific name, common name, taxon ID, threshold]
const ROWS: [string, string, number, number][] = [
  ["Melospiza melodia", "Song Sparrow", 9100, 0.3],
  ["Turdus migratorius", "American Robin", 12727, 0.35],
  ["Troglodytes pacificus", "Pacific Wren", 144882, 0.55],
  ["Pipilo maculatus", "Spotted Towhee", 9420, 0.3],
  ["Catharus ustulatus", "Swainson's Thrush", 12878, 0.3],
  ["Thryomanes bewickii", "Bewick's Wren", 7576, 0.3],
  ["Colaptes auratus", "Northern Flicker", 18236, 0.3],
  ["Agelaius phoeniceus", "Red-winged Blackbird", 9744, 0.3],
  ["Poecile atricapillus", "Black-capped Chickadee", 144815, 0.35],
  ["Sitta canadensis", "Red-breasted Nuthatch", 14823, 0.3],
  ["Strix varia", "Barred Owl", 19893, 0.35],
  ["Corvus brachyrhynchos", "American Crow", 8021, 0.3],
  ["Junco hyemalis", "Dark-eyed Junco", 10094, 0.3],
  ["Cyanocitta stelleri", "Steller's Jay", 8234, 0.65],
  ["Ixoreus naevius", "Varied Thrush", 145088, 0.3],
  ["Haemorhous mexicanus", "House Finch", 199840, 0.3],
  ["Zonotrichia leucophrys", "White-crowned Sparrow", 9176, 0.3],
  ["Poecile rufescens", "Chestnut-backed Chickadee", 144820, 0.4],
  ["Empidonax difficilis", "Western Flycatcher", 16598, 0.3],
  ["Regulus satrapa", "Golden-crowned Kinglet", 117100, 0.3],
];

const AUDIO_ID_SPECIES = ROWS.map( ( [name, commonName, taxonId, threshold] ) => ( {
  name, commonName, taxonId, threshold,
} ) );

export default AUDIO_ID_SPECIES;
